#!/usr/bin/env bash
# ============================================================================
# deploy_testnet.sh — Deploy all Oraculum contracts to Stellar testnet
# ============================================================================
#
# This script:
#   1. Builds all contracts in release mode
#   2. Deploys each contract to testnet using `stellar contract deploy`
#   3. Initializes contracts with admin addresses
#   4. Records deployed contract addresses to a `.env` file
#   5. Is idempotent — skips contracts that are already deployed
#
# Usage:
#   ./deploy_testnet.sh
#   ./deploy_testnet.sh --admin GCXXXX... --network testnet
#
# Environment variables (or CLI flags):
#   ADMIN_ADDRESS   — Admin address for contract initialization
#   NETWORK         — Stellar network to deploy to (default: testnet)
#   SOROBAN_RPC_URL — RPC URL (default: https://soroban-testnet.stellar.org)
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTRACTS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACE_DIR="$CONTRACTS_DIR"
ENV_FILE="$SCRIPT_DIR/../.env.deployed"

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
NETWORK="testnet"
SOROBAN_RPC_URL="${SOROBAN_RPC_URL:-https://soroban-testnet.stellar.org}"
ADMIN_ADDRESS="${ADMIN_ADDRESS:-}"
CONTRACTS=(
    "access_control"
    "manage_hub"
    "membership_token"
    "common_types"
    "workspace_booking"
    "payment_escrow"
    "resource_credits"
)
WASM_DIR="$WORKSPACE_DIR/target/wasm32-unknown-unknown/release"

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --admin)
            ADMIN_ADDRESS="$2"
            shift 2
            ;;
        --network)
            NETWORK="$2"
            shift 2
            ;;
        --rpc-url)
            SOROBAN_RPC_URL="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 [--admin <address>] [--network <network>] [--rpc-url <url>]"
            echo ""
            echo "Deploy all Oraculum contracts to Stellar testnet."
            echo ""
            echo "Options:"
            echo "  --admin <address>   Admin address for contract initialization"
            echo "  --network <name>    Stellar network (default: testnet)"
            echo "  --rpc-url <url>     Soroban RPC URL"
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Validate prerequisites
# ---------------------------------------------------------------------------
if ! command -v stellar &>/dev/null; then
    echo "ERROR: 'stellar' CLI not found. Install the Stellar CLI first:" >&2
    echo "  https://soroban.stellar.org/docs/getting-started/setup" >&2
    exit 1
fi

if [[ -z "$ADMIN_ADDRESS" ]]; then
    echo "ERROR: --admin flag or ADMIN_ADDRESS environment variable is required." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Load existing deployments from .env file (idempotency)
# ---------------------------------------------------------------------------
declare -A DEPLOYED_ADDRESSES

load_deployed_addresses() {
    if [[ -f "$ENV_FILE" ]]; then
        while IFS='=' read -r key value; do
            # Skip comments and empty lines
            [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
            DEPLOYED_ADDRESSES["$key"]="$value"
        done < "$ENV_FILE"
        echo "Loaded ${#DEPLOYED_ADDRESSES[@]} existing deployment(s) from $ENV_FILE"
    fi
}

save_deployed_address() {
    local contract_name="$1"
    local address="$2"
    local env_key="CONTRACT_$(echo "$contract_name" | tr '[:lower:]' '[:upper:]')_ADDRESS"

    DEPLOYED_ADDRESSES["$env_key"]="$address"

    # Rebuild the env file
    {
        echo "# Oraculum Testnet Deployments"
        echo "# Generated by deploy_testnet.sh — do not edit manually"
        echo "# Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        echo ""
        for key in "${!DEPLOYED_ADDRESSES[@]}"; do
            echo "${key}=${DEPLOYED_ADDRESSES[$key]}"
        done
    } > "$ENV_FILE"
}

# ---------------------------------------------------------------------------
# Build all contracts
# ---------------------------------------------------------------------------
echo "============================================================================"
echo "  Building contracts for testnet deployment"
echo "============================================================================"
echo ""

cargo build \
    --release \
    --target wasm32-unknown-unknown \
    --manifest-path "$WORKSPACE_DIR/Cargo.toml" \
    2>&1

echo ""
echo "  Build completed."
echo ""

# ---------------------------------------------------------------------------
# Load existing deployments
# ---------------------------------------------------------------------------
load_deployed_addresses

# ---------------------------------------------------------------------------
# Deploy each contract
# ---------------------------------------------------------------------------
echo "============================================================================"
echo "  Deploying contracts to $NETWORK"
echo "============================================================================"
echo ""

for contract in "${CONTRACTS[@]}"; do
    wasm_file="$WASM_DIR/${contract}.wasm"
    env_key="CONTRACT_$(echo "$contract" | tr '[:lower:]' '[:upper:]')_ADDRESS"

    # Check if WASM file exists
    if [[ ! -f "$wasm_file" ]]; then
        echo "  WARNING: WASM not found for $contract at $wasm_file — skipping"
        continue
    fi

    # Check if already deployed (idempotent)
    if [[ -n "${DEPLOYED_ADDRESSES[$env_key]:-}" ]]; then
        echo "  SKIP: $contract already deployed at ${DEPLOYED_ADDRESSES[$env_key]}"
        continue
    fi

    echo "  Deploying $contract..."

    # Deploy using stellar CLI
    CONTRACT_ADDRESS=$(
        stellar contract deploy \
            --wasm "$wasm_file" \
            --network "$NETWORK" \
            --rpc-url "$SOROBAN_RPC_URL" \
            --source admin \
            2>&1 | tail -1
    )

    if [[ -z "$CONTRACT_ADDRESS" || "$CONTRACT_ADDRESS" == *"Error"* || "$CONTRACT_ADDRESS" == *"error"* ]]; then
        echo "  ERROR: Failed to deploy $contract"
        echo "  Output: $CONTRACT_ADDRESS"
        continue
    fi

    # Trim whitespace
    CONTRACT_ADDRESS=$(echo "$CONTRACT_ADDRESS" | xargs)

    echo "  Deployed $contract at: $CONTRACT_ADDRESS"
    save_deployed_address "$contract" "$CONTRACT_ADDRESS"
done

echo ""
echo "============================================================================"
echo "  Deployment Summary"
echo "============================================================================"
echo ""

if [[ -f "$ENV_FILE" ]]; then
    echo "  Deployed addresses saved to: $ENV_FILE"
    echo ""
    while IFS='=' read -r key value; do
        [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
        echo "  $key=$value"
    done < "$ENV_FILE"
else
    echo "  No deployments recorded."
fi

echo ""
echo "  To initialize contracts, run: ./init_testnet.sh"
