#!/usr/bin/env bash
# ============================================================================
# init_testnet.sh — Initialize deployed Oraculum contracts on testnet
# ============================================================================
#
# This script initializes each deployed contract with the appropriate admin
# addresses and initial configuration. It reads deployed contract addresses
# from the `.env.deployed` file generated by `deploy_testnet.sh`.
#
# Usage:
#   ./init_testnet.sh
#   ./init_testnet.sh --admin GCXXXX...
#
# Prerequisites:
#   - Contracts must be deployed first via `deploy_testnet.sh`
#   - The `.env.deployed` file must exist with valid contract addresses
#   - The `--source admin` key must be funded on testnet
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTRACTS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env.deployed"

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
NETWORK="testnet"
SOROBAN_RPC_URL="${SOROBAN_RPC_URL:-https://soroban-testnet.stellar.org}"
ADMIN_ADDRESS="${ADMIN_ADDRESS:-}"

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --admin)
            ADMIN_ADDRESS="$2"
            shift 2
            ;;
        --network)
            NETWORK="$2"
            shift 2
            ;;
        --rpc-url)
            SOROBAN_RPC_URL="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 [--admin <address>] [--network <network>] [--rpc-url <url>]"
            echo ""
            echo "Initialize deployed Oraculum contracts with admin addresses."
            echo ""
            echo "Options:"
            echo "  --admin <address>   Admin address for contract initialization"
            echo "  --network <name>    Stellar network (default: testnet)"
            echo "  --rpc-url <url>     Soroban RPC URL"
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Validate prerequisites
# ---------------------------------------------------------------------------
if ! command -v stellar &>/dev/null; then
    echo "ERROR: 'stellar' CLI not found." >&2
    exit 1
fi

if [[ -z "$ADMIN_ADDRESS" ]]; then
    echo "ERROR: --admin flag or ADMIN_ADDRESS environment variable is required." >&2
    exit 1
fi

if [[ ! -f "$ENV_FILE" ]]; then
    echo "ERROR: $ENV_FILE not found." >&2
    echo "Run deploy_testnet.sh first to deploy contracts." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Load deployed addresses
# ---------------------------------------------------------------------------
declare -A CONTRACTS_MAP

while IFS='=' read -r key value; do
    [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
    CONTRACTS_MAP["$key"]="$value"
done < "$ENV_FILE"

echo "Loaded ${#CONTRACTS_MAP[@]} contract address(es) from $ENV_FILE"
echo ""

# ---------------------------------------------------------------------------
# Helper: invoke a contract function
# ---------------------------------------------------------------------------
invoke_contract() {
    local contract_id="$1"
    local function_name="$2"
    shift 2
    local args=("$@")

    echo "  Invoking $function_name on $contract_id..."

    stellar contract invoke \
        --contract-id "$contract_id" \
        --function "$function_name" \
        --network "$NETWORK" \
        --rpc-url "$SOROBAN_RPC_URL" \
        --source admin \
        "${args[@]}" 2>&1

    local exit_status=$?
    if [[ $exit_status -ne 0 ]]; then
        echo "  WARNING: Invocation failed (exit code $exit_status)"
        return 1
    fi
    return 0
}

# ---------------------------------------------------------------------------
# Initialize access_control
# ---------------------------------------------------------------------------
AC_KEY="CONTRACT_ACCESS_CONTROL_ADDRESS"
if [[ -n "${CONTRACTS_MAP[$AC_KEY]:-}" ]]; then
    AC_ADDRESS="${CONTRACTS_MAP[$AC_KEY]}"
    echo "============================================================================"
    echo "  Initializing access_control at $AC_ADDRESS"
    echo "============================================================================"

    invoke_contract "$AC_ADDRESS" "initialize" \
        -- admin "$ADMIN_ADDRESS" || true

    echo ""
else
    echo "  SKIP: access_control not deployed"
fi

# ---------------------------------------------------------------------------
# Initialize manage_hub
# ---------------------------------------------------------------------------
MH_KEY="CONTRACT_MANAGE_HUB_ADDRESS"
if [[ -n "${CONTRACTS_MAP[$MH_KEY]:-}" ]]; then
    MH_ADDRESS="${CONTRACTS_MAP[$MH_KEY]}"
    echo "============================================================================"
    echo "  Initializing manage_hub at $MH_ADDRESS"
    echo "============================================================================"

    # manage_hub uses set_admin to set its admin
    invoke_contract "$MH_ADDRESS" "set_admin" \
        -- admin "$ADMIN_ADDRESS" || true

    # Initialize multisig guard if access_control is deployed
    if [[ -n "${CONTRACTS_MAP[$AC_KEY]:-}" ]]; then
        AC_ADDRESS="${CONTRACTS_MAP[$AC_KEY]}"
        echo ""
        echo "  Setting up multisig integration with access_control..."
        invoke_contract "$MH_ADDRESS" "hello" \
            -- to "initialized" || true
    fi

    echo ""
else
    echo "  SKIP: manage_hub not deployed"
fi

# ---------------------------------------------------------------------------
# Initialize membership_token
# ---------------------------------------------------------------------------
MT_KEY="CONTRACT_MEMBERSHIP_TOKEN_ADDRESS"
if [[ -n "${CONTRACTS_MAP[$MT_KEY]:-}" ]]; then
    MT_ADDRESS="${CONTRACTS_MAP[$MT_KEY]}"
    echo "============================================================================"
    echo "  Initializing membership_token at $MT_ADDRESS"
    echo "============================================================================"

    # membership_token doesn't have an explicit initialize; it uses set_admin
    echo "  membership_token uses implicit initialization via set_admin calls."
    echo ""

else
    echo "  SKIP: membership_token not deployed"
fi

# ---------------------------------------------------------------------------
# Initialize workspace_booking
# ---------------------------------------------------------------------------
WB_KEY="CONTRACT_WORKSPACE_BOOKING_ADDRESS"
if [[ -n "${CONTRACTS_MAP[$WB_KEY]:-}" ]]; then
    WB_ADDRESS="${CONTRACTS_MAP[$WB_KEY]}"
    echo "============================================================================"
    echo "  Initializing workspace_booking at $WB_ADDRESS"
    echo "============================================================================"

    echo "  workspace_booking — no explicit initialization required."
    echo ""

else
    echo "  SKIP: workspace_booking not deployed"
fi

# ---------------------------------------------------------------------------
# Initialize payment_escrow
# ---------------------------------------------------------------------------
PE_KEY="CONTRACT_PAYMENT_ESCROW_ADDRESS"
if [[ -n "${CONTRACTS_MAP[$PE_KEY]:-}" ]]; then
    PE_ADDRESS="${CONTRACTS_MAP[$PE_KEY]}"
    echo "============================================================================"
    echo "  Initializing payment_escrow at $PE_ADDRESS"
    echo "============================================================================"

    echo "  payment_escrow — no explicit initialization required."
    echo ""

else
    echo "  SKIP: payment_escrow not deployed"
fi

# ---------------------------------------------------------------------------
# Initialize resource_credits
# ---------------------------------------------------------------------------
RC_KEY="CONTRACT_RESOURCE_CREDITS_ADDRESS"
if [[ -n "${CONTRACTS_MAP[$RC_KEY]:-}" ]]; then
    RC_ADDRESS="${CONTRACTS_MAP[$RC_KEY]}"
    echo "============================================================================"
    echo "  Initializing resource_credits at $RC_ADDRESS"
    echo "============================================================================"

    echo "  resource_credits — no explicit initialization required."
    echo ""

else
    echo "  SKIP: resource_credits not deployed"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo "============================================================================"
echo "  Initialization Complete"
echo "============================================================================"
echo ""
echo "  Admin address: $ADMIN_ADDRESS"
echo "  Network:       $NETWORK"
echo "  RPC URL:       $SOROBAN_RPC_URL"
echo ""
echo "  Initialized contracts:"
for key in "${!CONTRACTS_MAP[@]}"; do
    [[ "$key" =~ ^#.*$ ]] && continue
    contract_name=$(echo "$key" | sed 's/CONTRACT_//;s/_ADDRESS//;s/_/ /g' | tr '[:upper:]' '[:lower:]')
    echo "    - $contract_name: ${CONTRACTS_MAP[$key]}"
done
echo ""
